jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set working dir to backend
        working-directory: backend
        run: echo "Working in backend folder"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        working-directory: backend

      - name: Install dependencies
        run: bundle install
        working-directory: backend

      - name: Run RuboCop
        run: bin/rubocop -f github
        working-directory: backend
